const mongoose = require('mongoose');
const Schema = mongoose.Schema;
var passportLocalMongoose = require('passport-local-mongoose');

var User = new Schema({
    //Username and password is for basic authentication 
    //Now the username password field will be generated by passport-local-mongoose
    /*username : {
        type:String,
        required:true,
        unique:true
    },
    password : {
        type : String,
        required:true
    },*/
    firstname : {
        type:String,
        default:''
    },
    lastname : {
        type:String,
        default:''
    },
    admin :{
        type: Boolean,
        default: false
    }
});
User.plugin(passportLocalMongoose);//Will add username and hashed password field using salt and add addition methods
                                    //useful for passport authentication


module.exports = mongoose.model('User', User);